# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/umber/OneDrive/Desktop/project/work_dir/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/umber/OneDrive/Desktop/project/work_dir/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/umber/AppData/Roaming/Xilinx/Vivado/2019.2/xhub/board_store} [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
set_property ip_repo_paths {
  c:/Users/umber/OneDrive/Desktop/project/IP_repo
  c:/Users/umber/OneDrive/Desktop/display
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/umber/OneDrive/Desktop/project/work_dir/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/hdl/design_1_wrapper.v
add_files C:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_uartlite_1_0/design_1_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_uartlite_1_0/design_1_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_uartlite_1_0/design_1_axi_uartlite_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_d_axi_i2s_audio_0_0/src/fifo_4/fifo_4.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_d_axi_i2s_audio_0_0/src/fifo_4/fifo_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_d_axi_i2s_audio_0_0/src/fifo_32/fifo_32.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_d_axi_i2s_audio_0_0/src/fifo_32/fifo_32_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_d_axi_i2s_audio_0_0/src/d_axi_i2s_audio.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_fir_filter_0_0/constraints/fir_filter_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/design_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/umber/OneDrive/Desktop/project/IP_repo/design_1/ip/design_1_microblaze_0_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/umber/OneDrive/Desktop/project/work_dir/project_1.srcs/constrs_1/new/Zybo.xdc
set_property used_in_implementation false [get_files C:/Users/umber/OneDrive/Desktop/project/work_dir/project_1.srcs/constrs_1/new/Zybo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
